version: '3.5'

services:

  namenode:
    image: bde2020/hadoop-namenode:${HADOOP_VERSION}
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ./ficheros:/ficheros
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020

  datanode1:
    image: bde2020/hadoop-datanode:${HADOOP_VERSION}
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1_data:/hadoop/dfs/data
      - ./ficheros:/ficheros
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HDFS_CONF_dfs_datanode_address: "0.0.0.0:7001"
      HDFS_CONF_dfs_datanode_ipc_address: "0.0.0.0:7101"
      HDFS_CONF_dfs_datanode_http_address: "0.0.0.0:7201"
    depends_on:
      - namenode
    ports:
      - 7001:7001
      - 7101:7101
      - 7201:7201

  datanode2:
    image: bde2020/hadoop-datanode:${HADOOP_VERSION}
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2_data:/hadoop/dfs/data
      - ./ficheros:/ficheros
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HDFS_CONF_dfs_datanode_address: "0.0.0.0:7002"
      HDFS_CONF_dfs_datanode_ipc_address: "0.0.0.0:7102"
      HDFS_CONF_dfs_datanode_http_address: "0.0.0.0:7202"
    depends_on:
      - namenode
    ports:
      - 7002:7002
      - 7102:7102
      - 7202:7202

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
