version: '3.5'

services:

  https-portal:
    image: steveltn/https-portal:1
    environment:
      DOMAINS: >
        namenode -> http://namenode:9870,
        datanode1 -> http://datanode1:9864,
        datanode2 -> http://datanode2:9864,
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - namenode
    networks:
      main:
        ipv4_address: 172.27.10.1

  namenode:
    image: bde2020/hadoop-namenode:${HADOOP_VERSION}
    hostname: namenode
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ./ficheros:/ficheros
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    expose:
      - 9870
    ports:
      - 8020:8020
    networks:
      main:
        ipv4_address: 172.27.20.1

  datanode1:
    image: bde2020/hadoop-datanode:${HADOOP_VERSION}
    hostname: datanode1
    volumes:
      - datanode1_data:/hadoop/dfs/data
      - ./ficheros:/ficheros
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    expose:
      - 9864
    ports:
      - 9866:9866
    networks:
      main:
        ipv4_address: 172.27.20.2

  datanode2:
    image: bde2020/hadoop-datanode:${HADOOP_VERSION}
    hostname: datanode2
    volumes:
      - datanode2_data:/hadoop/dfs/data
      - ./ficheros:/ficheros
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    expose:
      - 9864
    networks:
      main:
        ipv4_address: 172.27.20.3

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16

volumes:
  https-portal_certs:
  namenode_data:
  datanode1_data:
  datanode2_data:
